// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package groundstation

import "strconv"

type RadioState int8

const (
	RadioStateIDLE         RadioState = 0
	RadioStateTRANSMITTING RadioState = 1
	RadioStateRECEIVING    RadioState = 2
	RadioStateCOOLDOWN     RadioState = 3
)

var EnumNamesRadioState = map[RadioState]string{
	RadioStateIDLE:         "IDLE",
	RadioStateTRANSMITTING: "TRANSMITTING",
	RadioStateRECEIVING:    "RECEIVING",
	RadioStateCOOLDOWN:     "COOLDOWN",
}

var EnumValuesRadioState = map[string]RadioState{
	"IDLE":         RadioStateIDLE,
	"TRANSMITTING": RadioStateTRANSMITTING,
	"RECEIVING":    RadioStateRECEIVING,
	"COOLDOWN":     RadioStateCOOLDOWN,
}

func (v RadioState) String() string {
	if s, ok := EnumNamesRadioState[v]; ok {
		return s
	}
	return "RadioState(" + strconv.FormatInt(int64(v), 10) + ")"
}
