// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package groundstation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SR0PacketData struct {
	_tab flatbuffers.Table
}

func GetRootAsSR0PacketData(buf []byte, offset flatbuffers.UOffsetT) *SR0PacketData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SR0PacketData{}
	x.Init(buf, n+offset)
	return x
}

func FinishSR0PacketDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSR0PacketData(buf []byte, offset flatbuffers.UOffsetT) *SR0PacketData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SR0PacketData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSR0PacketDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SR0PacketData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SR0PacketData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SR0PacketData) Header(obj *PacketHeader) *PacketHeader {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PacketHeader)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SR0PacketData) PacketBody(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SR0PacketData) PacketBodyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SR0PacketData) PacketBodyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SR0PacketData) MutatePacketBody(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func SR0PacketDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SR0PacketDataAddHeader(builder *flatbuffers.Builder, header flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(header), 0)
}
func SR0PacketDataAddPacketBody(builder *flatbuffers.Builder, packetBody flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(packetBody), 0)
}
func SR0PacketDataStartPacketBodyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SR0PacketDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
